/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiCastSol from './MultiCast.sol';
export type { multiCastSol };
import type * as testSol from './Test.sol';
export type { testSol };
export type { Multicast } from './MultiCast.sol/Multicast';
export type { TestStorage } from './Test.sol/TestStorage';
