/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiCastSol from "./MultiCast.sol";
export type { multiCastSol };
import type * as testSol from "./Test.sol";
export type { testSol };
export * as factories from "./factories";
export type { Multicast } from "./MultiCast.sol/Multicast";
export { Multicast__factory } from "./factories/MultiCast.sol/Multicast__factory";
export type { TestStorage } from "./Test.sol/TestStorage";
export { TestStorage__factory } from "./factories/Test.sol/TestStorage__factory";
